import type { StemGradeBand, StemSubtype } from './stem-types'

export const STEM_CATEGORY_SUBJECTS = ['mathematics', 'physics', 'chemistry', 'biology'] as const
export type StemCategorySubject = typeof STEM_CATEGORY_SUBJECTS[number]

export type StemActivityConfig = {
  complexity: string
  variables: readonly string[]
  expectedOutput: string
}

export type StemCurriculumCategory = {
  id: string
  label: string
  coveredTopics: readonly string[]
  activityPattern: readonly string[]
  toolSubtypes: readonly StemSubtype[]
  activity_config: Readonly<Record<StemGradeBand, StemActivityConfig>>
}

export type StemCurriculumCategorySubject = {
  subject: StemCategorySubject
  label: string
  categories: readonly StemCurriculumCategory[]
}

const scale = (focus: string, foundational: string, developing: string, advanced: string, expert: string): Readonly<Record<StemGradeBand, StemActivityConfig>> => ({
  grade_1_3: { complexity: foundational, variables: [`${focus} with concrete examples`, 'guided prompts', 'one-step decisions'], expectedOutput: 'A labeled observation or simple answer.' },
  grade_4_6: { complexity: developing, variables: [`${focus} with changing values`, 'visual comparisons', 'multi-step prompts'], expectedOutput: 'A recorded result with a short explanation.' },
  grade_7_9: { complexity: advanced, variables: [`${focus} with numeric or symbolic inputs`, 'independent choices', 'evidence-based checks'], expectedOutput: 'A calculated or analyzed result supported by evidence.' },
  grade_10_12: { complexity: expert, variables: [`${focus} with abstract or real-world data`, 'multiple constraints', 'model evaluation'], expectedOutput: 'A justified conclusion, model, or solution.' },
})

const category = (id: string, label: string, coveredTopics: readonly string[], activityPattern: readonly string[], toolSubtypes: readonly StemSubtype[], activityConfig: Readonly<Record<StemGradeBand, StemActivityConfig>>): StemCurriculumCategory => ({ id, label, coveredTopics, activityPattern, toolSubtypes, activity_config: activityConfig })
const tools = (...subtypes: StemSubtype[]): readonly StemSubtype[] => subtypes

const mathematics: StemCurriculumCategory[] = [
  category('number-counting', 'Number & Counting', ['Counting & Number Recognition', 'Place Value', 'Number Systems', 'Real Numbers', 'Integers', 'Sets', 'Large/Whole Numbers'], ['Represent Number', 'Compare Numbers', 'Build Number', 'Order Numbers', 'Practice Problem', 'Challenge'], tools('math.calculator', 'math.number_line', 'math.counting_visualizer'), scale('number representation', 'qualitative counting and comparison', 'place value and multi-step number work', 'signed, real, and set-based reasoning', 'abstract number systems and proof-style reasoning')),
  category('arithmetic-operations', 'Arithmetic Operations', ['Addition', 'Subtraction', 'Multiplication', 'Division', 'Operations', 'Factors & Multiples'], ['Demonstrate Operation', 'Change Operands', 'Visualize Result', 'Solve Problem', 'Word Problem', 'Challenge'], tools('math.calculator', 'math.graph'), scale('operation inputs', 'concrete operations within familiar ranges', 'multi-digit operations and factors', 'signed values and symbolic operations', 'complex operations in applied contexts')),
  category('fractions-decimals-ratios-percentages', 'Fractions/Decimals/Ratios/%', ['Fractions', 'Decimals', 'Ratios', 'Percentages'], ['Build Model', 'Convert Between Forms', 'Compare Values', 'Solve Problem', 'Real-World Application', 'Challenge'], tools('math.calculator', 'math.fraction_visualizer', 'math.graph'), scale('value representation', 'part-whole models and simple comparisons', 'conversions and proportional reasoning', 'multi-representation problem solving', 'complex proportional models and applications')),
  category('algebra-equations-functions', 'Algebra & Equations & Functions', ['Algebra', 'Linear/Quadratic/Simultaneous Equations', 'Functions', 'Polynomial', 'Exponential/Log', 'Trig Functions'], ['Build Expression', 'Solve Equation', 'Graph Function', 'Change Parameters & Observe', 'Check Solution', 'Challenge'], tools('math.graph', 'math.equation_solver', 'math.calculator'), scale('expression parameters', 'missing values and simple patterns', 'expressions and one-step equations', 'linear, quadratic, and simultaneous relationships', 'polynomial, exponential, logarithmic, and trigonometric models')),
  category('geometry-shapes', 'Geometry & Shapes', ['Shapes Around Us', '2D/3D Shapes', 'Geometry', 'Angles', 'Triangles', 'Circles', 'Transformations', 'Pythagorean Theorem', 'Similarity', 'Trigonometry', 'Analytical Geometry'], ['Construct Shape', 'Change Dimensions', 'Measure Angles/Sides', 'Calculate Area/Volume', 'Discover the Formula', 'Challenge'], tools('math.geometry_builder', 'math.calculator', 'math.graph'), scale('shape dimensions', 'recognition and guided construction', 'measurement and basic formulas', 'transformations, similarity, and coordinate geometry', 'trigonometric and analytical geometry reasoning')),
  category('measurement', 'Measurement', ['Length & Height', 'Weight & Balance', 'Time', 'Measurement', 'Area & Perimeter/Volume', 'Mensuration'], ['Measure Object', 'Compare Measurements', 'Convert Units', 'Estimate & Check', 'Solve Problem', 'Challenge'], tools('math.calculator', 'math.graph'), scale('measurement units', 'direct comparison and estimation', 'unit conversion and perimeter/area', 'compound measurements and volume', 'measurement models with precision and constraints')),
  category('money-finance', 'Money & Finance', ['Money', 'Financial Mathematics'], ['Identify Money', 'Make Change', 'Solve Money Problem', 'Budget Scenario', 'Challenge'], tools('math.calculator'), scale('money values', 'recognition and simple change', 'multi-step purchases and budgets', 'percentages, rates, and financial comparisons', 'compound financial models and decisions')),
  category('data-graphs-statistics-probability', 'Data/Graphs/Statistics/Probability', ['Data & Graphs', 'Statistics', 'Probability'], ['Collect/Enter Data', 'Build Graph', 'Read Graph', 'Calculate Statistic', 'Predict Outcome', 'Analyze Results'], tools('math.graph', 'math.calculator'), scale('data sets', 'sorting and reading simple displays', 'tables, graphs, and basic probability', 'statistics and probability calculations', 'statistical inference and model interpretation')),
  category('patterns-sequences', 'Patterns & Sequences', ['Patterns', 'Sequences & Series'], ['Identify Pattern', 'Extend Pattern', 'Build Own Pattern', 'Find the Rule', 'Challenge'], tools('math.graph', 'math.calculator'), scale('sequence rules', 'visual repetition and extension', 'numeric rules and table patterns', 'sequence formulas and graphs', 'series behavior and applications')),
  category('sorting-classification', 'Sorting & Classification', ['Sorting & Classification'], ['Sort Items', 'Check Grouping', 'Define Category Rule', 'Challenge'], tools('math.calculator'), scale('classification rules', 'concrete sorting by one property', 'multiple properties and explicit rules', 'formal sets and logical conditions', 'classification models and decision criteria')),
  category('coordinate-geometry-vectors', 'Coordinate Geometry & Vectors', ['Coordinate Grids/Geometry', 'Vectors'], ['Plot Points', 'Transform Coordinates', 'Calculate Distance/Slope', 'Vector Operation', 'Challenge'], tools('math.graph', 'math.calculator'), scale('coordinate inputs', 'plotting points on a grid', 'translations and distance', 'slope, vectors, and coordinate proofs', 'vector operations and analytical models')),
  category('calculus', 'Calculus', ['Limits', 'Differentiation', 'Integration', 'Applications'], ['Graph Function', 'Explore Rate of Change/Area', 'Compute Derivative/Integral', 'Apply to Problem', 'Challenge'], tools('math.graph', 'math.calculator'), scale('function behavior', 'visual change and area intuition', 'rate and accumulation previews', 'limits and introductory derivatives', 'derivatives, integrals, and applications')),
  category('mathematical-modelling', 'Mathematical Modelling', ['Mathematical Modelling'], ['Define Scenario', 'Build Model', 'Test Against Data', 'Refine Model', 'Challenge'], tools('math.graph', 'math.calculator'), scale('scenario variables', 'representing a familiar situation', 'building a simple table or rule', 'testing equations against data', 'evaluating and refining real-world models')),
]

const physics: StemCurriculumCategory[] = [
  category('forces-motion', 'Forces & Motion', ['Push & Pull', 'Movement', 'Forces & Motion', 'Force', 'Friction', 'Gravity', "Newton's Laws", 'Momentum', 'Kinematics', 'Dynamics', 'Circular/Linear Motion', 'Advanced Mechanics'], ['Measure Speed', 'Change Distance/Time', 'Observe Motion Graph', 'Compare Two Objects', 'Calculate Average Speed', 'Virtual Experiment', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.graph', 'physics.formula_solver'), scale('motion variables', 'qualitative push, pull, and movement', 'speed and distance comparisons', 'force, mass, acceleration, and momentum', 'advanced mechanics and constrained models')),
  category('energy-work-heat', 'Energy, Work & Heat', ['Energy', 'Work', 'Heat', 'Heat Transfer', 'Thermal Physics', 'Oscillations'], ['Change Input Variable', 'Observe Energy Transfer', 'Calculate Value', 'Virtual Experiment', 'Record Observations', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.graph', 'physics.formula_solver'), scale('energy inputs', 'observe simple heating and movement', 'compare energy transfer', 'work, power, and thermal calculations', 'thermal physics and oscillation models')),
  category('light-optics', 'Light & Optics', ['Light & Shadows', 'Light', 'Reflection', 'Refraction'], ['Change Light Source/Angle', 'Observe Shadow/Reflection', 'Predict Outcome', 'Record Observations', 'Analyze Results', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.graph'), scale('light angle and source', 'shadows and light direction', 'reflection and simple ray paths', 'reflection, refraction, and measurement', 'optical models and quantitative analysis')),
  category('sound-waves', 'Sound & Waves', ['Sound & Vibrations', 'Sound', 'Vibrations', 'Waves'], ['Change Frequency/Amplitude', 'Observe Wave Pattern', 'Compare Sounds', 'Record Observations', 'Analyze Results', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.graph'), scale('wave properties', 'vibration and sound comparisons', 'frequency and amplitude observations', 'wave graphs and calculations', 'wave models and analysis')),
  category('electricity-magnetism', 'Electricity & Magnetism', ['Magnets', 'Electricity', 'Electrostatics', 'Electric Fields', 'Current Electricity', 'Magnetism', 'Electromagnetic Induction', 'Semiconductor Electronics'], ['Build Circuit/Setup', 'Change Variable', 'Observe Effect', 'Calculate Value', 'Virtual Experiment', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.graph', 'physics.circuit_builder'), scale('circuit and field variables', 'magnetic and electrical effects', 'simple circuits and current', 'fields, induction, and circuit calculations', 'electromagnetic and semiconductor models')),
  category('matter-fluids', 'Matter & Fluids', ['Floating & Sinking', 'Pressure', 'Fluid Mechanics', 'Properties of Matter'], ['Change Object/Variable', 'Observe Behavior', 'Predict Outcome', 'Record Observations', 'Analyze Results', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.formula_solver'), scale('material and fluid variables', 'floating, sinking, and observable properties', 'pressure and density comparisons', 'fluid calculations and matter properties', 'fluid mechanics and constrained systems')),
  category('modern-atomic-physics', 'Modern & Atomic Physics', ['Modern Physics', 'Atomic Physics', 'Nuclear Physics'], ['Explore Model/Diagram', 'Change Parameter', 'Observe Effect', 'Calculate Value', 'Challenge'], tools('physics.simulation', 'physics.graph'), scale('atomic model parameters', 'guided model exploration', 'simple particle and energy comparisons', 'atomic structure and modern physics relationships', 'nuclear and modern physics models')),
  category('measurement-vectors', 'Measurement & Vectors', ['Measurement', 'Vectors & Scalars', 'Experimental Methods'], ['Take Measurement', 'Record Data', 'Compare Method', 'Calculate Result', 'Challenge'], tools('physics.experiment', 'physics.graph', 'physics.formula_solver'), scale('measurement inputs', 'taking and comparing direct measurements', 'units and recorded data', 'vectors, uncertainty, and experimental methods', 'experimental design and quantitative evaluation')),
  category('simple-machines', 'Simple Machines', ['Simple Machines'], ['Build Setup', 'Change Load/Effort', 'Observe Mechanical Advantage', 'Calculate Value', 'Challenge'], tools('physics.simulation', 'physics.experiment', 'physics.formula_solver'), scale('load and effort', 'identify familiar machines', 'compare load and effort', 'mechanical advantage calculations', 'machine models with efficiency constraints')),
]

const chemistry: StemCurriculumCategory[] = [
  category('materials-states-matter', 'Materials & States of Matter', ['Materials Around Us', 'Solids/Liquids/Gases', 'Properties of Materials', 'Matter', 'States of Matter', 'Particle Model'], ['Identify/Sort Material', 'Change State', 'Observe Property', 'Record Observations', 'Analyze Results', 'Challenge'], tools('chemistry.simulation', 'chemistry.experiment', 'chemistry.periodic_table'), scale('material properties', 'identify and sort familiar materials', 'compare states and observable properties', 'particle models and changes of state', 'matter properties and model-based analysis')),
  category('mixtures-solutions-separation', 'Mixtures, Solutions & Separation', ['Mixing Materials', 'Dissolving', 'Mixtures', 'Solutions', 'Separation Methods', 'Solubility'], ['Mix Substances', 'Change Variable', 'Observe Result', 'Separate Mixture', 'Record Observations', 'Analyze Results'], tools('chemistry.simulation', 'chemistry.experiment'), scale('mixture variables', 'mix and observe familiar substances', 'dissolving and simple separation', 'solutions, solubility, and separation methods', 'quantitative solution and separation analysis')),
  category('chemical-physical-changes', 'Chemical & Physical Changes', ['Changes in Materials', 'Physical/Chemical Changes', 'Reversible & Irreversible Changes', 'Chemical Reactions', 'Chemical Kinetics', 'Equilibrium'], ['Trigger Change', 'Observe Reaction', 'Compare Before/After', 'Predict Outcome', 'Record Observations', 'Analyze Results'], tools('chemistry.simulation', 'chemistry.experiment', 'chemistry.graph'), scale('change variables', 'observe and describe a change', 'compare reversible and irreversible changes', 'reaction evidence and reaction rates', 'kinetics and equilibrium models')),
  category('atomic-structure-periodic-table', 'Atomic Structure & Periodic Table', ['Atomic & Particle Models', 'Atomic Structure', 'Periodic Table', 'Periodic Properties/Trends', 'Elements & Compounds'], ['Explore Element/Model', 'Find Selected Elements', 'Compare Properties', 'Build Structure Diagram', 'Challenge'], tools('chemistry.periodic_table', 'chemistry.molecule_builder', 'chemistry.formula_solver'), scale('element properties', 'identify familiar elements and models', 'compare elements and simple structures', 'periodic trends and atomic structure', 'quantitative atomic and periodic models')),
  category('bonding-quantitative-chemistry', 'Bonding & Quantitative Chemistry', ['Chemical Bonding', 'Chemical Formulae', 'Mole Concept', 'Stoichiometry'], ['Build Molecule/Formula', 'Balance Equation', 'Calculate Quantity', 'Check Structure', 'Challenge'], tools('chemistry.molecule_builder', 'chemistry.chemical_equation', 'chemistry.formula_solver'), scale('formula inputs', 'build simple particle representations', 'formulae and basic balancing', 'moles and stoichiometric calculations', 'quantitative bonding and reaction models')),
  category('acids-bases-salts', 'Acids, Bases & Salts', ['Acids & Bases', 'Salts', 'Indicators'], ['Test Unknown Substance', 'pH Indicator Simulation', 'Compare Acidity', 'Neutralization Experiment', 'Predict pH', 'Record Observations', 'Analyze Results'], tools('chemistry.simulation', 'chemistry.experiment', 'chemistry.formula_solver'), scale('pH variables', 'classify familiar substances safely', 'indicator colors and simple comparisons', 'pH, neutralization, and concentration', 'acid-base equilibria and quantitative prediction')),
  category('water-chemistry', 'Water Chemistry', ['Water Around Us', 'Water Purification', 'Water Properties/Chemistry'], ['Test Water Sample', 'Change Variable', 'Observe Result', 'Record Observations', 'Analyze Results', 'Challenge'], tools('chemistry.simulation', 'chemistry.experiment'), scale('water sample variables', 'observe water properties', 'compare samples and filtration', 'purification and water chemistry', 'water quality and chemical analysis')),
  category('metals-non-metals', 'Metals & Non-Metals', ['Metals & Non-Metals'], ['Compare Properties', 'Test Reaction', 'Record Observations', 'Analyze Results', 'Challenge'], tools('chemistry.periodic_table', 'chemistry.simulation', 'chemistry.experiment'), scale('material properties', 'sort materials by visible properties', 'compare common metals and non-metals', 'reactivity and periodic relationships', 'materials selection and reaction analysis')),
  category('organic-chemistry', 'Organic Chemistry', ['Organic Chemistry', 'Hydrocarbons', 'Alcohols & Ethers', 'Aldehydes & Ketones', 'Carboxylic Acids', 'Polymers', 'Biochemistry'], ['Build Molecule/Structure', 'Identify Functional Group', 'Predict Reaction', 'Record Observations', 'Analyze Results', 'Challenge'], tools('chemistry.molecule_builder', 'chemistry.chemical_equation', 'chemistry.simulation'), scale('molecular structures', 'recognize simple carbon-based models', 'build and compare basic structures', 'functional groups and reaction prediction', 'organic reactions, polymers, and biochemical models')),
  category('electrochemistry-redox', 'Electrochemistry & Redox', ['Oxidation & Reduction', 'Electrochemistry', 'Redox Reactions'], ['Build Cell/Setup', 'Change Variable', 'Observe Reaction', 'Calculate Value', 'Challenge'], tools('chemistry.simulation', 'chemistry.experiment', 'chemistry.formula_solver'), scale('cell variables', 'observe simple transfer and reaction effects', 'compare cells and visible reactions', 'redox relationships and electrochemical calculations', 'electrochemical cells and quantitative redox models')),
  category('lab-safety-techniques', 'Lab Safety & Techniques', ['Safe Use of Materials', 'Laboratory Safety/Techniques'], ['Identify Hazard', 'Choose Correct Procedure', 'Simulate Safe Setup', 'Challenge'], tools('chemistry.experiment', 'chemistry.simulation'), scale('safe procedure choices', 'identify familiar hazards', 'choose safe equipment and procedures', 'apply laboratory techniques and controls', 'evaluate safe experimental design')),
  category('environmental-chemistry', 'Environmental Chemistry', ['Environmental Chemistry', 'Air & Environmental Chemistry'], ['Explore Scenario', 'Change Variable', 'Observe Impact', 'Record Observations', 'Analyze Results'], tools('chemistry.simulation', 'chemistry.experiment', 'chemistry.graph'), scale('environmental variables', 'observe simple environmental changes', 'compare air and material impacts', 'analyze environmental chemistry data', 'evaluate scenarios with evidence and models')),
]

const biology: StemCurriculumCategory[] = [
  category('living-things-classification', 'Living Things & Classification', ['Living & Non-Living Things', 'Animal Classification'], ['Sort Items into Categories', 'Check Classification', 'Define Rule', 'Challenge'], tools('biology.classification_builder', 'biology.interactive_diagram'), scale('classification rules', 'sort familiar living and non-living examples', 'group organisms by visible traits', 'define classification rules and compare groups', 'evaluate classification models and evidence')),
  category('plants', 'Plants', ['Parts of Plants', 'Plant Structure', 'Seeds & Germination', 'Photosynthesis', 'Plant Reproduction', 'Roots/Stems/Leaves', 'Plant Nutrition/Transport/Physiology', 'Plant Tissues'], ['Light vs No Light', 'Carbon Dioxide Investigation', 'Leaf Test Simulation', 'Observe Oxygen Production', 'Change Light Intensity', 'Analyze Results'], tools('biology.simulation', 'biology.experiment', 'biology.interactive_diagram'), scale('plant growth variables', 'identify parts and observe growth', 'germination and plant needs', 'photosynthesis, transport, and reproduction', 'plant physiology and experimental analysis')),
  category('animals', 'Animals', ['Animals Around Us', 'Animal Groups/Needs/Adaptations/Nutrition/Physiology'], ['Explore Diagram/Model', 'Compare Adaptations', 'Match Animal to Habitat/Trait', 'Record Observations', 'Challenge'], tools('biology.interactive_diagram', 'biology.classification_builder', 'biology.simulation'), scale('animal traits', 'match animals to familiar traits', 'compare groups and habitats', 'adaptation, nutrition, and physiology', 'comparative animal models and evidence')),
  category('human-body-systems', 'Human Body Systems', ['Human Body Parts', 'Human Skeleton', 'Muscles', 'Digestive/Respiratory/Circulatory Systems', 'Human Nutrition/Reproduction', 'Coordination', 'Excretion', 'Transport Systems', 'Tissues & Organs'], ['Explore 3D/Diagram Model', 'Find Selected Parts', 'Trace Process/Pathway', 'Record Observations', 'Analyze Results', 'Challenge'], tools('biology.three_d_explorer', 'biology.interactive_diagram', 'biology.simulation'), scale('body system pathways', 'identify parts and simple functions', 'trace a basic body process', 'compare systems and transport pathways', 'integrated physiology and evidence-based analysis')),
  category('senses-health', 'Senses & Health', ['Our Five Senses', 'Food & Nutrition', 'Healthy Habits', 'Hygiene & Health'], ['Match Sense/Habit to Example', 'Test Scenario', 'Record Observations', 'Analyze Results', 'Challenge'], tools('biology.simulation', 'biology.experiment', 'biology.interactive_diagram'), scale('health scenarios', 'match senses and healthy choices', 'compare food, habits, and hygiene scenarios', 'analyze health evidence and systems', 'evaluate health scenarios using data')),
  category('cells', 'Cells', ['Cells Introduction', 'Cell Structure/Biology', 'Microscopes/Microscopy', 'Cell Functions/Division', 'Biological Molecules', 'Enzymes'], ['Inspect 3D Cell Model', 'Find Selected Parts', 'Change Variable', 'Observe Process', 'Record Observations', 'Challenge'], tools('biology.three_d_explorer', 'biology.interactive_diagram', 'biology.simulation'), scale('cell model variables', 'identify basic cell parts', 'compare cells and microscope observations', 'cell functions, molecules, and division', 'enzymes, molecular biology, and cell process models')),
  category('genetics-molecular-biology', 'Genetics & Molecular Biology', ['Genetics', 'Molecular Biology/Genetics', 'DNA & RNA', 'Biotechnology'], ['Cross Traits (Punnett Square)', 'Calculate Trait Percentages', 'Explore DNA/Model', 'Predict Outcome', 'Challenge'], tools('biology.genetics_punnett_square', 'biology.interactive_diagram', 'biology.simulation'), scale('trait and DNA variables', 'predict simple inherited traits', 'calculate basic trait percentages', 'model DNA and inheritance patterns', 'evaluate genetic and biotechnology models')),
  category('ecology-environment', 'Ecology & Environment', ['Habitats', 'Caring for Nature', 'Ecosystems', 'Environmental Conservation', 'Ecology', 'Biodiversity', 'Food Chains', 'Population Biology', 'Evolution', 'Conservation Biology'], ['Change Population/Environmental Variable', 'Observe Growth/Impact Over Time', 'Compare Scenarios', 'Record Observations', 'Analyze Results', 'Challenge'], tools('biology.simulation', 'biology.experiment', 'biology.graph'), scale('population and environment variables', 'observe habitats and simple food chains', 'compare ecosystem changes', 'population, biodiversity, and conservation data', 'evolutionary and environmental models')),
  category('microbiology-immunology', 'Microbiology & Immunology', ['Microbiology', 'Immunology'], ['Explore Model/Diagram', 'Compare Types', 'Record Observations', 'Analyze Results', 'Challenge'], tools('biology.interactive_diagram', 'biology.simulation', 'biology.experiment'), scale('microbe and immune variables', 'recognize helpful and harmful examples', 'compare types and simple responses', 'microbiology and immune system models', 'analyze microbial and immune interactions')),
  category('scientific-investigation', 'Scientific Investigation', ['Biology & Scientific Investigation'], ['Form Hypothesis', 'Design Virtual Experiment', 'Record Observations', 'Analyze Results', 'Draw Conclusion'], tools('biology.experiment', 'biology.simulation', 'biology.graph'), scale('investigation variables', 'ask a question and record an observation', 'plan a guided comparison', 'test a hypothesis with controlled variables', 'design and evaluate an investigation')),
]

export const STEM_CURRICULUM_CATEGORY_SUBJECTS: readonly StemCurriculumCategorySubject[] = [
  { subject: 'mathematics', label: 'Mathematics', categories: mathematics },
  { subject: 'physics', label: 'Physics', categories: physics },
  { subject: 'chemistry', label: 'Chemistry', categories: chemistry },
  { subject: 'biology', label: 'Biology', categories: biology },
]

export type StemCurriculumCategoryValidation = {
  valid: boolean
  subjectCount: number
  categoryCount: number
  coveredTopicCount: number
  emptyCategories: string[]
  duplicateCategoryIds: string[]
  sourceMatchSummary: string
}

export const validateStemCurriculumCategories = (subjects: readonly StemCurriculumCategorySubject[] = STEM_CURRICULUM_CATEGORY_SUBJECTS): StemCurriculumCategoryValidation => {
  const categories = subjects.flatMap((entry) => entry.categories.map((item) => `${entry.subject}:${item.id}`))
  const emptyCategories = subjects.flatMap((entry) => entry.categories.filter((item) => !item.coveredTopics.length || !item.activityPattern.length || !item.toolSubtypes.length).map((item) => `${entry.label} · ${item.label}`))
  const duplicateCategoryIds = categories.filter((id, index) => categories.indexOf(id) !== index)
  const categoryCount = subjects.reduce((total, entry) => total + entry.categories.length, 0)
  const coveredTopicCount = subjects.reduce((total, entry) => total + entry.categories.reduce((subjectTotal, item) => subjectTotal + item.coveredTopics.length, 0), 0)
  const valid = subjects.length === STEM_CATEGORY_SUBJECTS.length && subjects.every((entry) => STEM_CATEGORY_SUBJECTS.includes(entry.subject)) && emptyCategories.length === 0 && duplicateCategoryIds.length === 0
  return {
    valid,
    subjectCount: subjects.length,
    categoryCount,
    coveredTopicCount,
    emptyCategories,
    duplicateCategoryIds,
    sourceMatchSummary: valid ? 'Matches the supplied subject-level category patterns for Mathematics, Physics, Chemistry, and Biology.' : 'Does not match the supplied subject-level category pattern requirements.',
  }
}

export const STEM_CURRICULUM_CATEGORY_VALIDATION = validateStemCurriculumCategories()
