import type { StemSubject, StemTool } from './stem-types'

export type ActivityTool = {
  label: string
  implementation: StemTool
}

export type ActivityTopic = {
  topic: string
  tools: readonly ActivityTool[]
}

export type ActivityGrade = {
  grade: number
  topics: readonly ActivityTopic[]
}

export type ActivityCurriculum = Record<StemSubject, readonly ActivityGrade[]>

const t = (topic: string, tools: readonly [string, StemTool][]): ActivityTopic => ({
  topic,
  tools: tools.map(([label, implementation]) => ({ label, implementation })),
})

const g = (grade: number, topics: readonly ActivityTopic[]): ActivityGrade => ({ grade, topics })

const math: readonly ActivityGrade[] = [
  g(1, [
    t('Counting & Number Recognition', [['Number Counter', 'counting_visualizer'], ['Number Line', 'number_line'], ['Number Matcher', 'shape_matcher']]),
    t('Comparing Numbers', [['Number Comparator', 'calculator'], ['Number Line', 'number_line']]),
    t('Addition & Subtraction', [['Counter Blocks', 'counting_visualizer'], ['Number Line', 'number_line'], ['Equation Builder', 'equation_solver']]),
    t('Shapes Around Us', [['Shape Builder', 'geometry_builder'], ['Shape Matcher', 'shape_matcher']]),
    t('Patterns', [['Pattern Builder', 'graph'], ['Missing Pattern', 'calculator']]),
    t('Length & Height', [['Virtual Ruler', 'geometry_builder'], ['Length Comparator', 'calculator']]),
    t('Weight & Balance', [['Balance Scale', 'geometry_builder'], ['Weight Comparator', 'calculator']]),
    t('Time', [['Clock Builder', 'geometry_builder'], ['Time Matcher', 'calculator']]),
    t('Money', [['Coin Counter', 'counting_visualizer'], ['Money Builder', 'calculator']]),
    t('Sorting & Classification', [['Sorting Tool', 'shape_matcher'], ['Classification Challenge', 'calculator']]),
  ]),
  g(2, [
    t('Place Value', [['Place Value Blocks', 'counting_visualizer'], ['Number Builder', 'number_line']]),
    t('Addition', [['Addition Builder', 'calculator'], ['Number Line', 'number_line']]),
    t('Subtraction', [['Subtraction Builder', 'calculator'], ['Number Line', 'number_line']]),
    t('Multiplication Concepts', [['Array Builder', 'geometry_builder'], ['Multiplication Grid', 'graph']]),
    t('Division Concepts', [['Sharing Tool', 'counting_visualizer'], ['Division Builder', 'calculator']]),
    t('Fractions', [['Fraction Builder', 'fraction_visualizer'], ['Fraction Number Line', 'number_line']]),
    t('2D Shapes', [['Shape Builder', 'geometry_builder'], ['Shape Sorter', 'shape_matcher']]),
    t('3D Objects', [['3D Shape Explorer', 'geometry_builder'], ['Shape Matcher', 'shape_matcher']]),
    t('Measurement', [['Virtual Ruler', 'geometry_builder'], ['Measurement Lab', 'calculator']]),
    t('Time & Calendar', [['Clock Builder', 'geometry_builder'], ['Calendar Tool', 'calculator']]),
    t('Money', [['Money Counter', 'counting_visualizer'], ['Change Builder', 'calculator']]),
    t('Data & Graphs', [['Data Collector', 'calculator'], ['Graph Builder', 'graph']]),
    t('Patterns', [['Pattern Builder', 'graph'], ['Pattern Predictor', 'calculator']]),
  ]),
  g(3, [
    t('Numbers to Thousands', [['Place Value Builder', 'counting_visualizer'], ['Number Line', 'number_line']]),
    t('Addition & Subtraction', [['Equation Builder', 'equation_solver'], ['Number Line', 'number_line']]),
    t('Multiplication', [['Multiplication Grid', 'graph'], ['Array Builder', 'geometry_builder']]),
    t('Division', [['Division Builder', 'calculator'], ['Sharing Simulator', 'counting_visualizer']]),
    t('Fractions', [['Fraction Builder', 'fraction_visualizer'], ['Fraction Number Line', 'number_line']]),
    t('Measurement', [['Measurement Lab', 'calculator'], ['Unit Converter', 'calculator']]),
    t('Perimeter', [['Perimeter Builder', 'geometry_builder'], ['Perimeter Calculator', 'calculator']]),
    t('Area', [['Area Grid', 'geometry_builder'], ['Area Calculator', 'calculator']]),
    t('Geometry', [['Shape Builder', 'geometry_builder'], ['Geometry Explorer', 'geometry_builder']]),
    t('Angles', [['Angle Builder', 'geometry_builder'], ['Angle Measurer', 'calculator']]),
    t('Time', [['Clock Builder', 'geometry_builder'], ['Time Calculator', 'calculator']]),
    t('Money', [['Money Calculator', 'calculator'], ['Change Builder', 'calculator']]),
    t('Data & Graphs', [['Data Collector', 'calculator'], ['Graph Builder', 'graph']]),
    t('Patterns', [['Pattern Builder', 'graph'], ['Pattern Predictor', 'calculator']]),
  ]),
  g(4, [
    t('Large Numbers', [['Number Builder', 'counting_visualizer'], ['Place Value Explorer', 'number_line']]),
    t('Operations', [['Equation Builder', 'equation_solver'], ['Calculation Tool', 'calculator']]),
    t('Factors & Multiples', [['Factor Explorer', 'calculator'], ['Multiplication Grid', 'graph']]),
    t('Fractions', [['Fraction Builder', 'fraction_visualizer'], ['Fraction Calculator', 'calculator']]),
    t('Decimals', [['Decimal Number Line', 'number_line'], ['Decimal Calculator', 'calculator']]),
    t('Measurement', [['Measurement Lab', 'calculator'], ['Unit Converter', 'calculator']]),
    t('Area & Perimeter', [['Shape Grid', 'geometry_builder'], ['Area/Perimeter Calculator', 'calculator']]),
    t('Angles', [['Angle Builder', 'geometry_builder'], ['Protractor', 'geometry_builder']]),
    t('Symmetry', [['Symmetry Builder', 'geometry_builder'], ['Mirror Tool', 'geometry_builder']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Shape Builder', 'geometry_builder']]),
    t('Data Collection', [['Data Collector', 'calculator'], ['Table Builder', 'graph']]),
    t('Graphs', [['Bar Graph Builder', 'graph'], ['Line Graph Builder', 'graph']]),
    t('Probability', [['Probability Spinner', 'calculator'], ['Probability Simulator', 'graph']]),
  ]),
  g(5, [
    t('Whole Numbers', [['Number Line', 'number_line'], ['Calculation Builder', 'calculator']]),
    t('Fractions', [['Fraction Builder', 'fraction_visualizer'], ['Fraction Calculator', 'calculator']]),
    t('Decimals', [['Decimal Calculator', 'calculator'], ['Decimal Number Line', 'number_line']]),
    t('Ratios', [['Ratio Builder', 'calculator'], ['Ratio Table', 'graph']]),
    t('Percentages', [['Percentage Calculator', 'calculator'], ['Percentage Grid', 'geometry_builder']]),
    t('Factors & Multiples', [['Factor Tree', 'geometry_builder'], ['Multiple Finder', 'calculator']]),
    t('Measurement', [['Measurement Lab', 'calculator'], ['Unit Converter', 'calculator']]),
    t('Area & Volume', [['Geometry Grid', 'geometry_builder'], ['Volume Calculator', 'calculator']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Shape Builder', 'geometry_builder']]),
    t('Coordinate Grids', [['Coordinate Plane', 'graph'], ['Point Plotter', 'graph']]),
    t('Data & Statistics', [['Data Table', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Spinner', 'calculator']]),
  ]),
  g(6, [
    t('Integers', [['Integer Number Line', 'number_line'], ['Integer Calculator', 'calculator']]),
    t('Fractions & Decimals', [['Fraction/Decimal Converter', 'calculator'], ['Number Line', 'number_line']]),
    t('Ratios & Proportions', [['Ratio Table', 'graph'], ['Proportion Builder', 'calculator']]),
    t('Percentages', [['Percentage Calculator', 'calculator'], ['Percentage Model', 'geometry_builder']]),
    t('Algebra Introduction', [['Expression Builder', 'equation_solver'], ['Algebra Tiles', 'geometry_builder']]),
    t('Equations', [['Equation Builder', 'equation_solver'], ['Balance Model', 'geometry_builder']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Shape Builder', 'geometry_builder']]),
    t('Area & Volume', [['Area/Volume Calculator', 'calculator'], ['3D Builder', 'geometry_builder']]),
    t('Coordinates', [['Coordinate Plane', 'graph'], ['Point Plotter', 'graph']]),
    t('Statistics', [['Data Table', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Spinner', 'calculator']]),
    t('Financial Mathematics', [['Money Calculator', 'calculator'], ['Interest Calculator', 'calculator']]),
  ]),
  g(7, [
    t('Integers & Rational Numbers', [['Number Line', 'number_line'], ['Rational Number Builder', 'calculator']]),
    t('Algebraic Expressions', [['Algebra Tiles', 'geometry_builder'], ['Expression Builder', 'equation_solver']]),
    t('Linear Equations', [['Equation Builder', 'equation_solver'], ['Balance Model', 'geometry_builder']]),
    t('Ratios & Proportions', [['Ratio Table', 'graph'], ['Proportion Graph', 'graph']]),
    t('Percentages', [['Percentage Calculator', 'calculator'], ['Percentage Model', 'geometry_builder']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Shape Builder', 'geometry_builder']]),
    t('Angles', [['Angle Builder', 'geometry_builder'], ['Protractor', 'geometry_builder']]),
    t('Triangles', [['Triangle Builder', 'geometry_builder'], ['Triangle Solver', 'calculator']]),
    t('Circles', [['Circle Builder', 'geometry_builder'], ['Circle Calculator', 'calculator']]),
    t('Area & Volume', [['Measurement Calculator', 'calculator'], ['3D Geometry', 'geometry_builder']]),
    t('Coordinate Geometry', [['Coordinate Plane', 'graph'], ['Graph Plotter', 'graph']]),
    t('Statistics', [['Data Analyzer', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Tree', 'geometry_builder']]),
  ]),
  g(8, [
    t('Real Numbers', [['Number Line', 'number_line'], ['Real Number Explorer', 'calculator']]),
    t('Algebra', [['Algebra Builder', 'equation_solver'], ['Expression Simplifier', 'calculator']]),
    t('Linear Equations', [['Equation Solver', 'equation_solver'], ['Graphing Tool', 'graph']]),
    t('Simultaneous Equations', [['System Graph', 'graph'], ['Equation Solver', 'equation_solver']]),
    t('Ratios & Proportions', [['Ratio Builder', 'calculator'], ['Proportion Graph', 'graph']]),
    t('Functions', [['Function Machine', 'calculator'], ['Function Grapher', 'graph']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Geometry Solver', 'calculator']]),
    t('Transformations', [['Transformation Builder', 'geometry_builder'], ['Coordinate Grid', 'graph']]),
    t('Pythagorean Theorem', [['Triangle Builder', 'geometry_builder'], ['Pythagorean Calculator', 'calculator']]),
    t('Mensuration', [['Area/Volume Calculator', 'calculator'], ['3D Geometry', 'geometry_builder']]),
    t('Statistics', [['Data Analyzer', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Tree', 'geometry_builder']]),
  ]),
  g(9, [
    t('Sets', [['Set Builder', 'calculator'], ['Venn Diagram', 'geometry_builder']]),
    t('Real Numbers', [['Number Line', 'number_line'], ['Number Calculator', 'calculator']]),
    t('Algebraic Expressions', [['Algebra Builder', 'equation_solver'], ['Expression Simplifier', 'calculator']]),
    t('Linear Equations', [['Equation Solver', 'equation_solver'], ['Graph Plotter', 'graph']]),
    t('Functions', [['Function Machine', 'calculator'], ['Function Grapher', 'graph']]),
    t('Coordinate Geometry', [['Coordinate Plane', 'graph'], ['Graph Plotter', 'graph']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Geometry Solver', 'calculator']]),
    t('Similarity', [['Similarity Builder', 'geometry_builder'], ['Scale Calculator', 'calculator']]),
    t('Pythagorean Theorem', [['Triangle Solver', 'calculator'], ['Pythagorean Calculator', 'calculator']]),
    t('Statistics', [['Data Analyzer', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Tree', 'geometry_builder']]),
    t('Mathematical Modelling', [['Model Builder', 'graph'], ['Graph Plotter', 'graph']]),
  ]),
  g(10, [
    t('Number Systems', [['Number Explorer', 'calculator'], ['Number Line', 'number_line']]),
    t('Algebra', [['Algebra Builder', 'equation_solver'], ['Expression Solver', 'calculator']]),
    t('Functions', [['Function Machine', 'calculator'], ['Function Grapher', 'graph']]),
    t('Quadratic Equations', [['Quadratic Solver', 'equation_solver'], ['Parabola Grapher', 'graph'], ['Root Finder', 'calculator']]),
    t('Sequences & Series', [['Sequence Builder', 'graph'], ['Series Calculator', 'calculator']]),
    t('Geometry', [['Geometry Canvas', 'geometry_builder'], ['Geometry Solver', 'calculator']]),
    t('Trigonometry', [['Trigonometry Circle', 'geometry_builder'], ['Trig Calculator', 'calculator']]),
    t('Coordinate Geometry', [['Coordinate Plane', 'graph'], ['Graph Plotter', 'graph']]),
    t('Statistics', [['Data Analyzer', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Tree', 'geometry_builder']]),
    t('Mathematical Modelling', [['Model Builder', 'graph'], ['Graph Plotter', 'graph']]),
  ]),
  g(11, [
    t('Functions', [['Function Machine', 'calculator'], ['Function Grapher', 'graph']]),
    t('Polynomial Functions', [['Polynomial Grapher', 'graph'], ['Root Finder', 'calculator']]),
    t('Exponential & Logarithmic Functions', [['Function Grapher', 'graph'], ['Log Calculator', 'calculator']]),
    t('Trigonometric Functions', [['Trig Grapher', 'graph'], ['Unit Circle', 'geometry_builder']]),
    t('Sequences & Series', [['Sequence Generator', 'graph'], ['Series Calculator', 'calculator']]),
    t('Analytical Geometry', [['Coordinate Plane', 'graph'], ['Geometry Solver', 'calculator']]),
    t('Vectors', [['Vector Builder', 'geometry_builder'], ['Vector Addition', 'calculator']]),
    t('Limits', [['Limit Explorer', 'graph'], ['Graph Analyzer', 'graph']]),
    t('Differentiation', [['Derivative Grapher', 'graph'], ['Derivative Calculator', 'calculator']]),
    t('Applications of Derivatives', [['Optimization Lab', 'calculator'], ['Tangent Explorer', 'graph']]),
    t('Statistics', [['Data Analyzer', 'graph'], ['Statistics Calculator', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Probability Distribution', 'calculator']]),
  ]),
  g(12, [
    t('Functions', [['Function Grapher', 'graph'], ['Function Analyzer', 'calculator']]),
    t('Advanced Algebra', [['Algebra Solver', 'equation_solver'], ['Expression Builder', 'calculator']]),
    t('Trigonometry', [['Unit Circle', 'geometry_builder'], ['Trig Grapher', 'graph']]),
    t('Vectors', [['Vector Builder', 'geometry_builder'], ['Vector Calculator', 'calculator']]),
    t('Analytical Geometry', [['Coordinate Geometry', 'graph'], ['Graph Plotter', 'graph']]),
    t('Limits', [['Limit Explorer', 'graph'], ['Limit Calculator', 'calculator']]),
    t('Differentiation', [['Derivative Lab', 'graph'], ['Derivative Grapher', 'graph']]),
    t('Applications of Differentiation', [['Optimization Lab', 'calculator'], ['Rate-of-Change Tool', 'graph']]),
    t('Integration', [['Integral Calculator', 'calculator'], ['Area Under Curve', 'graph']]),
    t('Applications of Integration', [['Area Calculator', 'calculator'], ['Volume of Revolution', 'geometry_builder']]),
    t('Statistics', [['Statistics Analyzer', 'graph'], ['Distribution Tool', 'calculator']]),
    t('Probability', [['Probability Simulator', 'graph'], ['Distribution Calculator', 'calculator']]),
    t('Mathematical Modelling', [['Model Builder', 'graph'], ['Data Grapher', 'graph']]),
  ]),
]

const physics: readonly ActivityGrade[] = [
  g(1, [
    t('Push & Pull', [['Push-Pull Explorer', 'simulation'], ['Force Matcher', 'experiment']]),
    t('Movement', [['Motion Simulator', 'simulation'], ['Movement Tracker', 'graph']]),
    t('Fast & Slow', [['Speed Comparator', 'simulation'], ['Motion Graph', 'graph']]),
    t('Light & Shadows', [['Light Source Lab', 'experiment'], ['Shadow Builder', 'simulation']]),
    t('Sound & Vibrations', [['Sound Simulator', 'simulation'], ['Vibration Viewer', 'experiment']]),
    t('Heat & Cold', [['Temperature Lab', 'experiment'], ['Heat Transfer Explorer', 'simulation']]),
    t('Magnets', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
    t('Floating & Sinking', [['Float-or-Sink Lab', 'experiment'], ['Density Explorer', 'simulation']]),
  ]),
  g(2, [
    t('Types of Movement', [['Motion Simulator', 'simulation'], ['Movement Graph', 'graph']]),
    t('Push & Pull', [['Force Explorer', 'simulation'], ['Force Matcher', 'experiment']]),
    t('Forces in Everyday Life', [['Force Simulator', 'simulation'], ['Force Diagram', 'graph']]),
    t('Light & Shadows', [['Light Source Lab', 'experiment'], ['Shadow Simulator', 'simulation']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Heat', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Magnets', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
    t('Floating & Sinking', [['Float-or-Sink Lab', 'experiment'], ['Density Simulator', 'simulation']]),
    t('Simple Machines', [['Machine Builder', 'simulation'], ['Lever Lab', 'experiment']]),
  ]),
  g(3, [
    t('Forces & Motion', [['Motion Simulator', 'simulation'], ['Force Diagram', 'graph']]),
    t('Friction', [['Friction Simulator', 'simulation'], ['Surface Selector', 'experiment']]),
    t('Gravity', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Light', [['Light Ray Simulator', 'simulation'], ['Light Source Lab', 'experiment']]),
    t('Reflection', [['Mirror Lab', 'experiment'], ['Ray Diagram Builder', 'graph']]),
    t('Shadows', [['Shadow Simulator', 'simulation'], ['Shadow Builder', 'graph']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Vibrations', [['Vibration Simulator', 'simulation'], ['Frequency Meter', 'formula_solver']]),
    t('Heat Transfer', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Magnets', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
    t('Simple Machines', [['Machine Builder', 'simulation'], ['Lever Lab', 'experiment']]),
  ]),
  g(4, [
    t('Measuring Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Force', [['Force Simulator', 'simulation'], ['Free-Body Diagram', 'graph']]),
    t('Friction', [['Friction Simulator', 'simulation'], ['Surface Selector', 'experiment']]),
    t('Gravity', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Energy', [['Energy Transformation Lab', 'experiment'], ['Energy Bar Chart', 'graph']]),
    t('Heat', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Light', [['Light Ray Simulator', 'simulation'], ['Light Source Lab', 'experiment']]),
    t('Reflection', [['Mirror Lab', 'experiment'], ['Ray Diagram Builder', 'graph']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity Introduction', [['Circuit Builder', 'circuit_builder'], ['Current Meter', 'formula_solver']]),
    t('Magnets', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
  ]),
  g(5, [
    t('Measurement', [['Measurement Lab', 'experiment'], ['Unit Converter', 'formula_solver'], ['Reading Scale', 'graph']]),
    t('Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph'], ['Speed Calculator', 'formula_solver']]),
    t('Forces', [['Force Simulator', 'simulation'], ['Free-Body Diagram', 'graph'], ["Newton's Law Calculator", 'formula_solver']]),
    t('Pressure', [['Pressure Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Work', [['Work Calculator', 'formula_solver'], ['Work Simulator', 'simulation']]),
    t('Energy', [['Energy Transformation Lab', 'experiment'], ['Energy Bar Chart', 'graph']]),
    t('Friction', [['Friction Simulator', 'simulation'], ['Surface Selector', 'experiment']]),
    t('Gravity', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Momentum', [['Collision Lab', 'experiment'], ['Momentum Calculator', 'formula_solver']]),
    t('Simple Machines', [['Lever Lab', 'experiment'], ['Pulley Lab', 'experiment'], ['Inclined Plane Lab', 'simulation']]),
    t('Mechanical Advantage', [['Mechanical Advantage Calculator', 'formula_solver'], ['Machine Builder', 'simulation']]),
    t('Efficiency', [['Efficiency Calculator', 'formula_solver'], ['Machine Lab', 'experiment']]),
  ]),
  g(6, [
    t('Measurement & Units', [['Measurement Lab', 'experiment'], ['Unit Converter', 'formula_solver']]),
    t('Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Force', [['Force Simulator', 'simulation'], ['Free-Body Diagram', 'graph']]),
    t('Pressure', [['Pressure Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Work & Energy', [['Work Simulator', 'simulation'], ['Energy Transformation Lab', 'experiment']]),
    t('Heat', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Light', [['Light Ray Simulator', 'simulation'], ['Light Source Lab', 'experiment']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity', [['Circuit Builder', 'circuit_builder'], ['Voltage Meter', 'formula_solver']]),
    t('Magnetism', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
    t('Simple Machines', [['Machine Builder', 'simulation'], ['Mechanical Advantage Calculator', 'formula_solver']]),
  ]),
  g(7, [
    t('Measurement', [['Measurement Lab', 'experiment'], ['Unit Converter', 'formula_solver']]),
    t('Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Speed & Velocity', [['Speed Calculator', 'formula_solver'], ['Velocity Graph', 'graph']]),
    t('Force', [['Force Simulator', 'simulation'], ['Newton\'s Law Calculator', 'formula_solver']]),
    t('Pressure', [['Pressure Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Work', [['Work Simulator', 'simulation'], ['Work Calculator', 'formula_solver']]),
    t('Energy', [['Energy Transformation Lab', 'experiment'], ['Energy Bar Chart', 'graph']]),
    t('Heat Transfer', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Light', [['Light Ray Simulator', 'simulation'], ['Light Source Lab', 'experiment']]),
    t('Reflection & Refraction', [['Mirror Lab', 'experiment'], ['Refraction Simulator', 'simulation']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity', [['Circuit Builder', 'circuit_builder'], ['Voltage Meter', 'formula_solver']]),
    t('Magnetism', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
  ]),
  g(8, [
    t('Measurement', [['Measurement Lab', 'experiment'], ['Unit Converter', 'formula_solver'], ['Reading Scale', 'graph']]),
    t('Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph'], ['Speed Calculator', 'formula_solver']]),
    t('Force & Newtonian Ideas', [['Force Simulator', 'simulation'], ['Free-Body Diagram', 'graph'], ["Newton's Law Calculator", 'formula_solver']]),
    t('Pressure', [['Pressure Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Work & Energy', [['Work Simulator', 'simulation'], ['Energy Transformation Lab', 'experiment'], ['Energy Bar Chart', 'graph']]),
    t('Heat', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Light', [['Light Ray Simulator', 'simulation'], ['Light Source Lab', 'experiment']]),
    t('Reflection', [['Mirror Lab', 'experiment'], ['Ray Diagram Builder', 'graph']]),
    t('Refraction', [['Refraction Simulator', 'simulation'], ['Refractive Index Calculator', 'formula_solver']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity', [['Circuit Builder', 'circuit_builder'], ['Voltage Meter', 'formula_solver']]),
    t('Magnetism', [['Magnet Explorer', 'simulation'], ['Magnetic Field Viewer', 'experiment']]),
  ]),
  g(9, [
    t('Measurement', [['Virtual Ruler', 'experiment'], ['Stopwatch', 'formula_solver'], ['Measurement Lab', 'experiment']]),
    t('Vectors & Scalars', [['Vector Builder', 'graph'], ['Vector Components Calculator', 'formula_solver']]),
    t('Motion', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Linear Motion', [['Motion Simulator', 'simulation'], ['Speed Calculator', 'formula_solver']]),
    t('Forces', [['Force Simulator', 'simulation'], ['Free-Body Diagram', 'graph']]),
    t("Newton's Laws", [['Force Simulator', 'simulation'], ["Newton's Law Calculator", 'formula_solver']]),
    t('Work, Energy & Power', [['Work Simulator', 'simulation'], ['Energy Bar Chart', 'graph'], ['Power Calculator', 'formula_solver']]),
    t('Momentum', [['Collision Lab', 'experiment'], ['Momentum Calculator', 'formula_solver']]),
    t('Gravitation', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Properties of Matter', [['Particle Model', 'simulation'], ['Density Calculator', 'formula_solver']]),
    t('Heat', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Waves', [['Wave Simulator', 'simulation'], ['Wavelength/Frequency Controls', 'formula_solver']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity', [['Circuit Builder', 'circuit_builder'], ['Current Meter', 'formula_solver']]),
  ]),
  g(10, [
    t('Vectors', [['Vector Builder', 'graph'], ['Vector Components Calculator', 'formula_solver']]),
    t('Kinematics', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Dynamics', [['Force Simulator', 'simulation'], ["Newton's Law Calculator", 'formula_solver']]),
    t('Circular Motion', [['Motion Simulator', 'simulation'], ['Force Calculator', 'formula_solver']]),
    t('Work & Energy', [['Work Simulator', 'simulation'], ['Energy Transformation Lab', 'experiment']]),
    t('Momentum', [['Collision Lab', 'experiment'], ['Momentum Calculator', 'formula_solver']]),
    t('Gravitation', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Fluid Mechanics', [['Fluid Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Thermal Physics', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Waves', [['Wave Simulator', 'simulation'], ['Wavelength/Frequency Controls', 'formula_solver']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electricity', [['Circuit Builder', 'circuit_builder'], ['Current Meter', 'formula_solver']]),
    t('Magnetism', [['Magnetic Field Simulator', 'simulation'], ['Current Control', 'formula_solver']]),
  ]),
  g(11, [
    t('Measurement & Experimental Methods', [['Measurement Lab', 'experiment'], ['Measurement Challenge', 'formula_solver']]),
    t('Kinematics', [['Motion Simulator', 'simulation'], ['Distance-Time Graph', 'graph']]),
    t('Dynamics', [['Force Simulator', 'simulation'], ["Newton's Law Calculator", 'formula_solver']]),
    t('Momentum', [['Collision Lab', 'experiment'], ['Momentum Calculator', 'formula_solver']]),
    t('Work & Energy', [['Work Simulator', 'simulation'], ['Energy Bar Chart', 'graph']]),
    t('Circular Motion', [['Motion Simulator', 'simulation'], ['Force Calculator', 'formula_solver']]),
    t('Gravitation', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Fluid Mechanics', [['Fluid Simulator', 'simulation'], ['Pressure Calculator', 'formula_solver']]),
    t('Thermal Physics', [['Heat Transfer Lab', 'experiment'], ['Temperature Graph', 'graph']]),
    t('Oscillations', [['Vibration Simulator', 'simulation'], ['Frequency Meter', 'formula_solver']]),
    t('Waves', [['Wave Simulator', 'simulation'], ['Wavelength/Frequency Controls', 'formula_solver']]),
    t('Electrostatics', [['Charge Explorer', 'simulation'], ['Electric Field Viewer', 'graph']]),
    t('Current Electricity', [['Circuit Builder', 'circuit_builder'], ['Current Meter', 'formula_solver']]),
    t('Magnetism', [['Magnetic Field Simulator', 'simulation'], ['Current Control', 'formula_solver']]),
  ]),
  g(12, [
    t('Advanced Mechanics', [['Motion Simulator', 'simulation'], ['Force Simulator', 'simulation']]),
    t('Gravitation', [['Gravity Simulator', 'simulation'], ['Weight Calculator', 'formula_solver']]),
    t('Oscillations', [['Vibration Simulator', 'simulation'], ['Frequency Meter', 'formula_solver']]),
    t('Waves', [['Wave Simulator', 'simulation'], ['Wavelength/Frequency Controls', 'formula_solver']]),
    t('Sound', [['Sound Simulator', 'simulation'], ['Sound Wave Visualizer', 'graph']]),
    t('Electrostatics', [['Charge Explorer', 'simulation'], ['Electric Field Viewer', 'graph']]),
    t('Electric Fields', [['Electric Field Viewer', 'graph'], ['Field Calculator', 'formula_solver']]),
    t('Current Electricity', [['Circuit Builder', 'circuit_builder'], ['Current Meter', 'formula_solver']]),
    t('Magnetism', [['Magnetic Field Simulator', 'simulation'], ['Current Control', 'formula_solver']]),
    t('Electromagnetic Induction', [['Magnetic Field Simulator', 'simulation'], ['Induction Calculator', 'formula_solver']]),
    t('Electromagnetic Waves', [['Wave Simulator', 'simulation'], ['Wave Graph', 'graph']]),
    t('Modern Physics', [['Particle Model', 'simulation'], ['Energy Calculator', 'formula_solver']]),
    t('Atomic Physics', [['Atom Builder', 'simulation'], ['Energy Level Graph', 'graph']]),
    t('Nuclear Physics', [['Radiation Explorer', 'simulation'], ['Radiation Detector', 'experiment']]),
    t('Semiconductor Electronics', [['Circuit Builder', 'circuit_builder'], ['Current Control', 'formula_solver']]),
  ]),
]

const chemistry: readonly ActivityGrade[] = [
  g(1, [
    t('Materials Around Us', [['Material Explorer', 'simulation'], ['Material Sorter', 'classification_builder']]),
    t('Solids, Liquids & Gases', [['States of Matter Lab', 'experiment'], ['Particle Viewer', 'simulation']]),
    t('Properties of Materials', [['Material Tester', 'experiment'], ['Property Sorter', 'classification_builder']]),
    t('Mixing Materials', [['Mixing Lab', 'experiment'], ['Material Mixer', 'simulation']]),
    t('Dissolving', [['Dissolving Lab', 'experiment'], ['Solubility Tester', 'simulation']]),
    t('Water Around Us', [['Water Explorer', 'simulation'], ['Water Use Lab', 'experiment']]),
    t('Changes in Materials', [['Change Lab', 'experiment'], ['Before/After Tool', 'simulation']]),
    t('Safe Use of Materials', [['Safety Lab', 'experiment'], ['Hazard Sorter', 'classification_builder']]),
  ]),
  g(2, [
    t('Properties of Solids', [['Solid Material Tester', 'experiment']]),
    t('Properties of Liquids', [['Liquid Tester', 'experiment']]),
    t('Properties of Gases', [['Gas Explorer', 'simulation']]),
    t('Mixing & Separating', [['Mixture Builder', 'molecule_builder'], ['Separation Lab', 'experiment']]),
    t('Dissolving', [['Dissolving Lab', 'experiment'], ['Solubility Tool', 'simulation']]),
    t('Changes Caused by Heating', [['Heating Lab', 'experiment'], ['Temperature Control', 'simulation']]),
    t('Water & Materials', [['Water Interaction Lab', 'experiment']]),
    t('Reversible & Irreversible Changes', [['Change Classifier', 'classification_builder'], ['Change Lab', 'experiment']]),
  ]),
  g(3, [
    t('Matter', [['Matter Explorer', 'simulation'], ['Particle Viewer', 'simulation']]),
    t('States of Matter', [['State-of-Matter Lab', 'experiment'], ['Particle Simulator', 'simulation']]),
    t('Properties of Materials', [['Material Tester', 'experiment']]),
    t('Mixtures', [['Mixture Builder', 'molecule_builder']]),
    t('Solutions', [['Solution Builder', 'molecule_builder']]),
    t('Separation Methods', [['Filtration Lab', 'experiment'], ['Separation Tool', 'simulation']]),
    t('Heating & Cooling', [['Temperature Lab', 'experiment']]),
    t('Changes of State', [['Phase Change Simulator', 'simulation']]),
    t('Water Properties', [['Water Explorer', 'simulation']]),
    t('Material Selection', [['Material Comparison Tool', 'classification_builder']]),
  ]),
  g(4, [
    t('Matter & Its Properties', [['Matter Explorer', 'simulation'], ['Property Tester', 'experiment']]),
    t('Physical Changes', [['Change Simulator', 'simulation']]),
    t('Chemical Changes', [['Reaction Explorer', 'simulation']]),
    t('Mixtures', [['Mixture Builder', 'molecule_builder']]),
    t('Solutions', [['Solution Builder', 'molecule_builder']]),
    t('Separation Techniques', [['Filtration Lab', 'experiment'], ['Evaporation Lab', 'experiment']]),
    t('Acids & Bases Introduction', [['pH Explorer', 'simulation'], ['Indicator Tester', 'experiment']]),
    t('Water Purification', [['Water Purification Lab', 'experiment']]),
    t('Materials & Their Uses', [['Material Selector', 'classification_builder']]),
    t('Everyday Chemistry', [['Chemistry Explorer', 'simulation']]),
  ]),
  g(5, [
    t('Particle Model of Matter', [['Particle Simulator', 'simulation']]),
    t('States of Matter', [['Particle Viewer', 'simulation'], ['Phase Change Lab', 'experiment']]),
    t('Physical & Chemical Changes', [['Change Classifier', 'classification_builder'], ['Reaction Lab', 'experiment']]),
    t('Mixtures', [['Mixture Builder', 'molecule_builder']]),
    t('Solutions', [['Solution Builder', 'molecule_builder'], ['Concentration Tool', 'formula_solver']]),
    t('Solubility', [['Solubility Lab', 'experiment']]),
    t('Separation Techniques', [['Separation Lab', 'experiment']]),
    t('Acids & Bases', [['pH Meter', 'formula_solver'], ['Indicator Lab', 'experiment']]),
    t('Water Chemistry', [['Water Tester', 'experiment']]),
    t('Chemical Safety', [['Safety Lab', 'experiment'], ['Hazard Identifier', 'classification_builder']]),
  ]),
  g(6, [
    t('Atomic & Particle Models', [['Atom Builder', 'molecule_builder'], ['Particle Explorer', 'simulation']]),
    t('Elements & Compounds', [['Element Builder', 'periodic_table'], ['Compound Builder', 'molecule_builder']]),
    t('Mixtures', [['Mixture Builder', 'molecule_builder']]),
    t('Solutions', [['Solution Builder', 'molecule_builder']]),
    t('Separation', [['Separation Lab', 'experiment']]),
    t('Chemical Reactions', [['Reaction Builder', 'chemical_equation']]),
    t('Acids & Bases', [['pH Meter', 'formula_solver'], ['Indicator Lab', 'experiment']]),
    t('Indicators', [['Indicator Tester', 'experiment']]),
    t('Metals & Non-Metals', [['Material Tester', 'experiment'], ['Periodic Table', 'periodic_table']]),
    t('Water Chemistry', [['Water Analysis Lab', 'experiment']]),
    t('Environmental Chemistry', [['Pollution Lab', 'simulation']]),
  ]),
  g(7, [
    t('Matter & Particles', [['Particle Simulator', 'simulation']]),
    t('Atomic Structure', [['Atom Builder', 'molecule_builder']]),
    t('Elements', [['Periodic Table Explorer', 'periodic_table']]),
    t('Compounds', [['Compound Builder', 'molecule_builder']]),
    t('Chemical Formulae', [['Formula Builder', 'formula_solver'], ['Formula Calculator', 'formula_solver']]),
    t('Chemical Reactions', [['Reaction Simulator', 'simulation']]),
    t('Acids & Bases', [['pH Lab', 'experiment'], ['Indicator Lab', 'experiment']]),
    t('Salts', [['Salt Builder', 'molecule_builder']]),
    t('Metals', [['Metal Reactivity Lab', 'experiment']]),
    t('Separation Techniques', [['Separation Lab', 'experiment']]),
    t('Water', [['Water Analysis Lab', 'experiment']]),
    t('Air & Environmental Chemistry', [['Air Quality Lab', 'experiment']]),
  ]),
  g(8, [
    t('Atomic Structure', [['Atom Builder', 'molecule_builder']]),
    t('Periodic Table Introduction', [['Interactive Periodic Table', 'periodic_table']]),
    t('Chemical Bonding Introduction', [['Bond Builder', 'molecule_builder']]),
    t('Chemical Formulae', [['Formula Builder', 'formula_solver']]),
    t('Chemical Reactions', [['Reaction Simulator', 'simulation']]),
    t('Acids, Bases & Salts', [['pH Lab', 'experiment'], ['Neutralization Lab', 'experiment']]),
    t('Metals & Non-Metals', [['Reactivity Lab', 'experiment']]),
    t('Solutions', [['Solution Builder', 'molecule_builder'], ['Concentration Calculator', 'formula_solver']]),
    t('Water', [['Water Analysis Lab', 'experiment']]),
    t('Air', [['Air Composition Lab', 'experiment']]),
    t('Environmental Chemistry', [['Pollution Simulator', 'simulation']]),
    t('Laboratory Safety', [['Safety Lab', 'experiment'], ['Hazard Identifier', 'classification_builder']]),
  ]),
  g(9, [
    t('Laboratory Techniques & Safety', [['Virtual Lab Bench', 'virtual_lab'], ['Safety Lab', 'experiment']]),
    t('Matter', [['Particle Simulator', 'simulation']]),
    t('Atomic Structure', [['Atom Builder', 'molecule_builder']]),
    t('Periodic Table', [['Interactive Periodic Table', 'periodic_table']]),
    t('Chemical Bonding', [['Bond Builder', 'molecule_builder'], ['Molecule Builder', 'molecule_builder']]),
    t('Chemical Formulae', [['Formula Builder', 'formula_solver']]),
    t('Chemical Reactions', [['Reaction Simulator', 'simulation']]),
    t('Mole Concept', [['Mole Calculator', 'formula_solver']]),
    t('Stoichiometry', [['Stoichiometry Calculator', 'formula_solver'], ['Reaction Builder', 'chemical_equation']]),
    t('Solutions', [['Solution Builder', 'molecule_builder'], ['Concentration Calculator', 'formula_solver']]),
    t('Acids & Bases', [['pH Lab', 'experiment'], ['Titration Lab', 'experiment']]),
    t('Environmental Chemistry', [['Environmental Lab', 'experiment']]),
  ]),
  g(10, [
    t('Atomic Structure', [['Atom Builder', 'molecule_builder']]),
    t('Periodic Properties', [['Periodic Table Explorer', 'periodic_table']]),
    t('Chemical Bonding', [['Molecular Builder', 'molecule_builder']]),
    t('Mole Concept', [['Mole Calculator', 'formula_solver']]),
    t('Stoichiometry', [['Stoichiometry Lab', 'experiment']]),
    t('Chemical Reactions', [['Reaction Simulator', 'simulation']]),
    t('States of Matter', [['Particle Simulator', 'simulation']]),
    t('Solutions', [['Solution Builder', 'molecule_builder']]),
    t('Acids & Bases', [['pH Lab', 'experiment'], ['Titration Lab', 'experiment']]),
    t('Oxidation & Reduction', [['Redox Lab', 'experiment'], ['Electron Transfer Tool', 'simulation']]),
    t('Organic Chemistry Introduction', [['Molecule Builder', 'molecule_builder']]),
    t('Environmental Chemistry', [['Environmental Chemistry Lab', 'experiment']]),
  ]),
  g(11, [
    t('Laboratory Techniques', [['Virtual Lab Bench', 'virtual_lab']]),
    t('Atomic Structure', [['Atom Builder', 'molecule_builder']]),
    t('Periodic Trends', [['Periodic Table Explorer', 'periodic_table']]),
    t('Chemical Bonding', [['Bond Builder', 'molecule_builder'], ['Molecular Geometry', 'molecule_builder']]),
    t('Stoichiometry', [['Stoichiometry Calculator', 'formula_solver']]),
    t('Thermochemistry', [['Heat/Reaction Lab', 'experiment'], ['Energy Calculator', 'formula_solver']]),
    t('Chemical Equilibrium', [['Equilibrium Simulator', 'simulation']]),
    t('Acids & Bases', [['pH Lab', 'experiment'], ['Titration Lab', 'experiment']]),
    t('Redox Reactions', [['Redox Simulator', 'simulation']]),
    t('Electrochemistry', [['Electrochemical Cell Builder', 'molecule_builder']]),
    t('Organic Chemistry', [['Organic Molecule Builder', 'molecule_builder']]),
    t('Hydrocarbons', [['Hydrocarbon Builder', 'molecule_builder']]),
    t('Environmental Chemistry', [['Environmental Lab', 'experiment']]),
  ]),
  g(12, [
    t('Chemical Kinetics', [['Reaction Rate Simulator', 'simulation'], ['Rate Graph', 'graph']]),
    t('Chemical Equilibrium', [['Equilibrium Simulator', 'simulation'], ['Equilibrium Graph', 'graph']]),
    t('Acids & Bases', [['pH Lab', 'experiment'], ['Titration Lab', 'experiment']]),
    t('Solubility Equilibrium', [['Solubility Simulator', 'simulation'], ['Ksp Calculator', 'formula_solver']]),
    t('Thermochemistry', [['Energy Diagram', 'graph'], ['Heat Calculator', 'formula_solver']]),
    t('Electrochemistry', [['Cell Builder', 'molecule_builder'], ['Voltage Calculator', 'formula_solver']]),
    t('Redox Chemistry', [['Redox Simulator', 'simulation']]),
    t('Organic Chemistry', [['Organic Molecule Builder', 'molecule_builder']]),
    t('Hydrocarbons', [['Hydrocarbon Builder', 'molecule_builder']]),
    t('Alcohols & Ethers', [['Organic Molecule Builder', 'molecule_builder']]),
    t('Aldehydes & Ketones', [['Reaction Builder', 'chemical_equation']]),
    t('Carboxylic Acids', [['Reaction Builder', 'chemical_equation']]),
    t('Polymers', [['Polymer Builder', 'molecule_builder']]),
    t('Biochemistry', [['Biomolecule Builder', 'molecule_builder']]),
    t('Environmental Chemistry', [['Environmental Simulator', 'simulation']]),
  ]),
]

const biology: readonly ActivityGrade[] = [
  g(1, [
    t('Living & Non-Living Things', [['Classification Sorter', 'classification_builder']]),
    t('Parts of Plants', [['Interactive Plant', 'interactive_diagram'], ['Plant Labeler', 'interactive_diagram']]),
    t('Seeds & Germination', [['Germination Lab', 'experiment']]),
    t('Animals Around Us', [['Animal Explorer', 'interactive_diagram']]),
    t('Human Body Parts', [['Body Explorer', 'three_d_explorer']]),
    t('Our Five Senses', [['Sense Matcher', 'classification_builder']]),
    t('Food & Nutrition', [['Food Sorter', 'classification_builder'], ['Healthy Plate Builder', 'interactive_diagram']]),
    t('Healthy Habits', [['Healthy Habits Challenge', 'classification_builder']]),
    t('Habitats', [['Habitat Builder', 'interactive_diagram'], ['Animal Matcher', 'classification_builder']]),
    t('Caring for Nature', [['Recycling Sorter', 'classification_builder'], ['Nature Challenge', 'simulation']]),
  ]),
  g(2, [
    t('Plant Parts', [['Plant Explorer', 'interactive_diagram'], ['Labeling Tool', 'interactive_diagram']]),
    t('Plant Needs', [['Plant Growth Lab', 'experiment']]),
    t('Seed Germination', [['Germination Simulator', 'simulation']]),
    t('Animal Groups', [['Animal Classifier', 'classification_builder']]),
    t('Animal Needs', [['Animal Needs Simulator', 'simulation']]),
    t('Human Body', [['Body Explorer', 'three_d_explorer']]),
    t('Healthy Food', [['Food Sorter', 'classification_builder']]),
    t('Senses', [['Sense Explorer', 'interactive_diagram']]),
    t('Life Cycles', [['Life Cycle Builder', 'interactive_diagram']]),
    t('Habitats', [['Habitat Builder', 'interactive_diagram']]),
  ]),
  g(3, [
    t('Plant Structure', [['Plant Explorer', 'interactive_diagram']]),
    t('Photosynthesis Introduction', [['Photosynthesis Explorer', 'simulation']]),
    t('Plant Life Cycles', [['Life Cycle Builder', 'interactive_diagram']]),
    t('Animal Classification', [['Animal Classifier', 'classification_builder']]),
    t('Animal Adaptations', [['Adaptation Simulator', 'simulation']]),
    t('Human Skeleton', [['Skeleton Explorer', 'three_d_explorer']]),
    t('Muscles & Movement', [['Movement Simulator', 'simulation']]),
    t('Digestion', [['Digestive System Explorer', 'interactive_diagram']]),
    t('Respiration', [['Breathing Simulator', 'simulation']]),
    t('Ecosystems', [['Ecosystem Builder', 'interactive_diagram']]),
  ]),
  g(4, [
    t('Plant Reproduction', [['Plant Reproduction Lab', 'experiment']]),
    t('Photosynthesis', [['Photosynthesis Simulator', 'simulation']]),
    t('Roots, Stems & Leaves', [['Plant Structure Explorer', 'interactive_diagram']]),
    t('Animal Adaptations', [['Adaptation Lab', 'experiment']]),
    t('Food Chains', [['Food Chain Builder', 'interactive_diagram']]),
    t('Human Digestive System', [['Digestive System Explorer', 'interactive_diagram']]),
    t('Respiratory System', [['Respiratory System Explorer', 'interactive_diagram']]),
    t('Circulatory System', [['Circulatory System Explorer', 'interactive_diagram']]),
    t('Hygiene & Health', [['Healthy Habits Challenge', 'classification_builder']]),
    t('Ecosystems', [['Ecosystem Builder', 'interactive_diagram']]),
  ]),
  g(5, [
    t('Cells Introduction', [['Cell Explorer', 'three_d_explorer']]),
    t('Plant Structure', [['Plant Explorer', 'interactive_diagram']]),
    t('Photosynthesis', [['Photosynthesis Lab', 'experiment']]),
    t('Plant Reproduction', [['Reproduction Explorer', 'interactive_diagram']]),
    t('Animal Classification', [['Animal Classifier', 'classification_builder']]),
    t('Human Body Systems', [['Human Body Explorer', 'three_d_explorer']]),
    t('Nutrition', [['Nutrition Builder', 'interactive_diagram']]),
    t('Respiration', [['Respiration Simulator', 'simulation']]),
    t('Ecosystems', [['Ecosystem Builder', 'interactive_diagram']]),
    t('Food Chains', [['Food Chain Builder', 'interactive_diagram']]),
    t('Environmental Conservation', [['Conservation Challenge', 'simulation']]),
  ]),
  g(6, [
    t('Cell Structure', [['Cell Explorer', 'three_d_explorer']]),
    t('Microscopes', [['Virtual Microscope', 'interactive_diagram']]),
    t('Plant Tissues', [['Tissue Explorer', 'interactive_diagram']]),
    t('Photosynthesis', [['Photosynthesis Lab', 'experiment']]),
    t('Plant Reproduction', [['Plant Reproduction Lab', 'experiment']]),
    t('Animal Classification', [['Classification Tool', 'classification_builder']]),
    t('Human Nutrition', [['Nutrition Lab', 'experiment']]),
    t('Respiration', [['Respiration Simulator', 'simulation']]),
    t('Circulation', [['Circulatory System Explorer', 'interactive_diagram']]),
    t('Ecosystems', [['Ecosystem Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
  ]),
  g(7, [
    t('Cell Structure', [['Cell Explorer', 'three_d_explorer']]),
    t('Microscopy', [['Virtual Microscope', 'interactive_diagram']]),
    t('Cell Functions', [['Cell Activity Explorer', 'interactive_diagram']]),
    t('Plant Nutrition', [['Plant Nutrition Lab', 'experiment']]),
    t('Photosynthesis', [['Photosynthesis Simulator', 'simulation']]),
    t('Plant Transport', [['Transport Simulator', 'simulation']]),
    t('Plant Reproduction', [['Reproduction Lab', 'experiment']]),
    t('Animal Nutrition', [['Nutrition Explorer', 'interactive_diagram']]),
    t('Respiration', [['Respiration Simulator', 'simulation']]),
    t('Circulation', [['Circulatory System Explorer', 'interactive_diagram']]),
    t('Excretion', [['Excretory System Explorer', 'interactive_diagram']]),
    t('Ecosystems', [['Ecosystem Simulator', 'simulation']]),
    t('Environmental Conservation', [['Conservation Challenge', 'simulation']]),
  ]),
  g(8, [
    t('Cell Biology', [['Cell Explorer', 'three_d_explorer']]),
    t('Tissues & Organs', [['Tissue Explorer', 'interactive_diagram'], ['Organ Builder', 'three_d_explorer']]),
    t('Plant Physiology', [['Plant Physiology Lab', 'experiment']]),
    t('Photosynthesis', [['Photosynthesis Simulator', 'simulation']]),
    t('Reproduction', [['Reproduction Explorer', 'interactive_diagram']]),
    t('Human Nutrition', [['Nutrition Lab', 'experiment']]),
    t('Respiration', [['Respiration Simulator', 'simulation']]),
    t('Circulation', [['Circulatory System Explorer', 'interactive_diagram']]),
    t('Excretion', [['Excretion System Explorer', 'interactive_diagram']]),
    t('Coordination', [['Nervous System Explorer', 'interactive_diagram']]),
    t('Ecology', [['Ecosystem Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
  ]),
  g(9, [
    t('Biology & Scientific Investigation', [['Scientific Investigation Lab', 'experiment']]),
    t('Cell Biology', [['Cell Explorer', 'three_d_explorer']]),
    t('Biological Molecules', [['Biomolecule Builder', 'three_d_explorer']]),
    t('Enzymes', [['Enzyme Activity Lab', 'experiment']]),
    t('Cell Division', [['Mitosis & Meiosis Lab', 'interactive_diagram']]),
    t('Plant Structure', [['Plant Explorer', 'interactive_diagram']]),
    t('Plant Nutrition', [['Plant Nutrition Lab', 'experiment']]),
    t('Photosynthesis', [['Photosynthesis Simulator', 'simulation']]),
    t('Animal Nutrition', [['Nutrition Lab', 'experiment']]),
    t('Respiration', [['Cellular Respiration Lab', 'experiment']]),
    t('Transport Systems', [['Transport Simulator', 'simulation']]),
    t('Ecology', [['Ecosystem Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
  ]),
  g(10, [
    t('Cell Biology', [['Cell Explorer', 'three_d_explorer']]),
    t('Biomolecules', [['Biomolecule Builder', 'three_d_explorer']]),
    t('Enzymes', [['Enzyme Lab', 'experiment']]),
    t('Cell Division', [['Mitosis & Meiosis Lab', 'interactive_diagram']]),
    t('Genetics Introduction', [['Genetics Lab', 'genetics_punnett_square'], ['Punnett Square', 'genetics_punnett_square']]),
    t('Plant Physiology', [['Plant Physiology Lab', 'experiment']]),
    t('Animal Physiology', [['Animal Systems Explorer', 'interactive_diagram']]),
    t('Human Body Systems', [['Human Body Explorer', 'three_d_explorer']]),
    t('Reproduction', [['Reproduction Explorer', 'interactive_diagram']]),
    t('Ecology', [['Ecosystem Simulator', 'simulation']]),
    t('Evolution', [['Evolution Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
  ]),
  g(11, [
    t('Cell Biology', [['Cell Explorer', 'three_d_explorer']]),
    t('Biological Molecules', [['Biomolecule Builder', 'three_d_explorer']]),
    t('Enzymes', [['Enzyme Activity Lab', 'experiment']]),
    t('Cell Division', [['Mitosis & Meiosis Lab', 'interactive_diagram']]),
    t('Genetics', [['Genetics Lab', 'genetics_punnett_square'], ['Punnett Square', 'genetics_punnett_square']]),
    t('Molecular Biology', [['DNA/RNA Explorer', 'interactive_diagram']]),
    t('Plant Physiology', [['Plant Physiology Lab', 'experiment']]),
    t('Animal Physiology', [['Animal Systems Explorer', 'interactive_diagram']]),
    t('Reproduction', [['Reproduction Lab', 'experiment']]),
    t('Microbiology', [['Microorganism Explorer', 'interactive_diagram']]),
    t('Ecology', [['Ecosystem Simulator', 'simulation']]),
    t('Evolution', [['Evolution Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
  ]),
  g(12, [
    t('Genetics', [['Genetics Lab', 'genetics_punnett_square'], ['Punnett Square', 'genetics_punnett_square']]),
    t('Molecular Genetics', [['Gene Explorer', 'interactive_diagram']]),
    t('DNA & RNA', [['DNA/RNA Builder', 'interactive_diagram']]),
    t('Biotechnology', [['Biotechnology Lab', 'experiment']]),
    t('Evolution', [['Evolution Simulator', 'simulation']]),
    t('Plant Physiology', [['Plant Physiology Lab', 'experiment']]),
    t('Animal Physiology', [['Animal Physiology Explorer', 'interactive_diagram']]),
    t('Human Reproduction', [['Reproductive System Explorer', 'interactive_diagram']]),
    t('Immunology', [['Immune System Simulator', 'simulation']]),
    t('Microbiology', [['Microbiology Lab', 'experiment']]),
    t('Ecology', [['Ecosystem Simulator', 'simulation']]),
    t('Population Biology', [['Population Simulator', 'simulation']]),
    t('Biodiversity', [['Biodiversity Explorer', 'interactive_diagram']]),
    t('Environmental Biology', [['Environmental Simulator', 'simulation']]),
    t('Conservation Biology', [['Conservation Challenge', 'simulation']]),
  ]),
]

export const ACTIVITY_CURRICULUM: ActivityCurriculum = { math, physics, chemistry, biology }

export const getActivityGrades = (subject: StemSubject) => ACTIVITY_CURRICULUM[subject]

export const getActivityTopics = (subject: StemSubject, grade: number) => getActivityGrades(subject).find((entry) => entry.grade === grade)?.topics ?? []

export const getActivityTopic = (subject: StemSubject, grade: number, topic: string) => getActivityTopics(subject, grade).find((entry) => entry.topic === topic)
